# If there are any caching issues with npm, i.e. installing an older version of a lib that isn't pulled down,
# uncomment the rimraf to force a full clean npm install

sudo: false
language: node_js
node_js:
  - '0.10'
before_install:
  - 'npm install -g bower'
  - 'npm install -g rimraf'
  - 'gem install bundler'
before_script:
  - 'bundle install'
  - 'bower install -V'
  - 'npm cache clean'
  - 'rimraf node_modules'
  - 'npm install'
  - 'npm run build'
  - 'npm run test'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6cfe200b39a0f4131485
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

cache:
  directories:
    - node_modules
    - bower_components
